### ISSUE TITLE
issue_NICK

### ISSUE THREAD

**Issue by joonseong11** [42Peer/irc#17]
# NICK 변경 안됨 문제
쉘 2개 켜서 JOIN #123 을 각각 들어간 뒤
두번째 애가 NICK hello 했는데 아무런 행동도 안나오고,
첫번째 애가 NICK hello 했는데 닉네임이 변경된다

- [x]  간헐적 닉네임 변경 안됨 문제 ✅
- [x]  irssi 로비에서 nick 변경하고 채널 들어가면 반영이 안되어있다. (해결됐는지 화인필요)
- [x] 닉네임에 ":Welcome" 까지 포함되는 문제
- [x] 유효한 닉네임 검사 (" ,*?!@.", 접두 "$:#&")

**Comment by Deanioche** [comment]
<details>
<summary><b>irssi 로비에서 nick 변경하고 채널 들어가면 반영이 안되어있다.</b></summary>

![image](https://user-images.githubusercontent.com/82714924/232449174-9894ab9b-a8f8-4fdb-b1f3-a1ab362a0593.png)
</details>

**Comment by Deanioche** [comment]
<details>
<summary><b>닉네임에  ":Welcome" 까지 포함되는 문제</b></summary>


<img width="414" alt="image" src="https://user-images.githubusercontent.com/66513003/232459442-0938a1f3-51f2-45eb-b4e4-33c522cb49a4.png">
<img width="414" alt="image" src="https://user-images.githubusercontent.com/66513003/232459880-0de2b2d1-3d46-444d-badc-81957d73afe1.png">

</details>
