### ISSUE TITLE
issue_PRIVMSG

### ISSUE THREAD

**Issue by joonseong11** [42Peer/irc#21]
# irssi <-> nc PRIVMSG 호환안됨
- [x] irssi에서 /privmsg 로 쓰면 동작 안함 (irssi 에서는 /msg 로 privmsg가 동작함)
- [x] irssi에서 PRIVMSG <channel> <msg> 쓰면 irssi 쿼리에서는 PRIVMSG <channel> <msg> 로 보이는 반면 nc에서는 정상 수신
- [x] nc에서 보낼 시 마찬가지로 irssi에서 보이지 않음

**Comment by joonseong11** [comment]
Nc irssi 메세지 보이지 않는 현상은
Join에서 유발된 문제일 확률이 높습니다 join에서 같이 해결해볼게요

**Comment by seo-wo** [comment]
해결완료
