### ISSUE TITLE
issue_server_looping

### ISSUE THREAD

**Issue by joonseong11** [42Peer/irc#23]
# irssi NICK _ 메세지 서버에 무한루프되어 보내짐
- [ ] irssi로 접속한뒤 오랜시간 방치하면, 서버에 NICK _ 라는 명령어가 무한정으로 들어온다. 무한루프가 돌게됨

<details>
<summary><b>중복된 닉네임으로 접속 시도시 아래 메세지가 서버로 계속 들어온다.</b></summary>

![image](https://user-images.githubusercontent.com/66513003/232664910-668e12dc-982c-4f52-9f4c-34c0f631b7d0.png)

</details>

NICK에서 이미 중복된 닉네임을 썼을 경우 에러메세지 형식이 안맞아서 irssi 가 인식을 못하게 되고, 그로인해서 계속 무한루프로 메세지를 보내는 것이 아닌가 의심하는 중입니다.

`:irc.local 433 * root :Nickname is already in use.` tcpflow 로 잡은 처음 접속할때 nick 등록절차중 중복된 경우
`:irc.local 433 jujeon root :Nickname is already in use.`tcpflow로 잡은 접속된 유저가 닉네임 바꿀대 중복된 경우 출력메세지

**Comment by Deanioche** [comment]
중복된 닉네임으로 여러번 접속 혹은 변경 시도시 발생하는것으로 추정

**Comment by joonseong11** [comment]
평가시간안엔 발생하지 않을 것 같기도 한데 문제 원인을 못찾겠네요

**Comment by Deanioche** [comment]
작업중
