### ISSUE TITLE
seowokim-channel_name_format

### ISSUE THREAD

**Issue by seo-wo** [42Peer/irc#31]
# 요약
- [x] 채널이름에 `<0x07, BELL>` 들어오면 안됨
- [x] 채널 이름의 시작은 '#' 외에도 '&'도 받게 수정해야함

## JOIN 으로 새로운 채널을 만들때 채널 이름으로 들어올 수 없는 사항이 있습니다.
JOIN 커맨드에서 채널 이름 마스킹 검사할때 BELL 체크해서 걸러내기
```
- <BELL, 0x07>
- <' '> 파싱단계에서 공백은 다른 인자로 인식되서 걸러진다. -> 고려할 필요 없다.
- <','> 파싱 단계에서 다른 인자로 인식되어 나눠진다. -> 고려할 필요 없다.
```

### 구현
- 채널 이름에 0x07, BELL 이 들어가면 ERR476 에러 발생

### 참조자료 
채널 이름은 문자열입니다(지정된 접두사 문자로 시작). 첫 번째 문자가 유효한 채널 유형 접두사 문자여야 한다는 요구 사항 외에 채널 이름에 대한 유일한 제한 사항은 공백(' ', 0x20), 컨트롤 G/BELL('^G', 0x07) 또는 쉼표(',', 0x2C)(프로토콜에서 목록 항목 구분 기호로 사용)를 포함할 수 없다는 것입니다.
[](url)https://modern.ircdocs.horse/#channels

## 채널 이름 마스킹
```
'#' : 다른 irc 서버에의 클라이언트들도 들어올 수 있는 채널
'&' : 같은 irc 서버에서의 클라이언트들만 들어올 수 있는 채널
```
지금 irssi에서 &123 이라는 채널로 접속하면 db에서는 처리가 안되서 아무기능이 안되지만, 화면에 보이기는 들어가는 것 처럼 보인다!

**Comment by seo-wo** [comment]
[수정]
`0x07 0x20 0x27` 만 안받게 수정
channel 시작은 `'#', '&'` 전부 받게 수정

**Comment by joonseong11** [comment]
작업중입니다...
