### ISSUE TITLE
dohyulee-NICK-error-issue

### ISSUE THREAD

**Issue by Deanioche** [42Peer/irc#49]
### 4/19 14:24 최신 dev에서 발견한 문제들
- [x] Irssi 중복 닉네임 처리가 동작 안함
    - 닉네임 뒤에 `_ 1 2 3.....` 붙는거
- [x]  닉 변경시 클라이언트 닉네임 표시 공간에 반영 안됨
- [x]  로비에서 닉네임 변경 뒤 채팅방들어가면 원래 닉까지 2개가 들어가짐 
    <img width="340" alt="image" src="https://user-images.githubusercontent.com/66513003/232975848-70d8bcf1-63e8-4b82-9cc2-e89c4bf9a409.png">

---
### NIck 이슈가 아닌 이슈 메모
- [x] 채팅이 본인한테는 두번 뜨는 문제
- [ ] part할때 에러 메세지
    <img width="309" alt="image" src="https://user-images.githubusercontent.com/66513003/232974974-9c7ef8cc-5d46-4289-b913-eb3e4f4c1fb4.png">
- [x] 채팅방에 있을때 WHO 커맨드 에러가 뜸 (무효 커맨드에 추가 필요)
  `421 :Unknown Command: WHO`
- [x] 채팅창에 접속중 멤버 리스트가 제대로 안뜸: 메시지 양식 변경하여 해결
    <img width="472" alt="image" src="https://user-images.githubusercontent.com/66513003/232990069-8c30571c-18aa-4e67-a9fc-ab47265e0211.png">

    <img width="1005" alt="image" src="https://user-images.githubusercontent.com/66513003/232985739-ad429854-c7cc-4707-85be-2622e26490cf.png">

- [x] Nick `* NICK dohyulee` 양식으로 안뜸

**Comment by dllee94** [comment]
- 채팅이 본인한테는 두번 뜨는 문제
(코드 추가)
<img width="802" alt="image" src="https://user-images.githubusercontent.com/129829529/232993651-d86918bf-0b28-4afa-9bf5-ad55602c3fd9.png">
(결과)
<img width="2142" alt="image" src="https://user-images.githubusercontent.com/129829529/232993355-552a4650-35dc-454a-a04e-29379ef21dd6.png">

**Comment by dllee94** [comment]
- 채팅방에 있을때 WHO 커맨드 에러가 뜸 (무효 커맨드에 추가 필요)
(코드 추가)
- Parsing.hpp에 WHO 추가
- Parsing.cpp의 checkCommand에 WHO 추가
- Handler.cpp의 figureCommand에 WHO 추가
<img width="565" alt="image" src="https://user-images.githubusercontent.com/129829529/232998805-f987b045-46e0-45c5-87b5-6bf57533a6ac.png">

(결과)
<img width="2117" alt="image" src="https://user-images.githubusercontent.com/129829529/232999190-fa629f81-6d25-4b70-b41f-1fd8237fe35b.png">
