### ISSUE TITLE
irssi에서 kick당했을때 출력양식이 안맞다.

### ISSUE THREAD

**Issue by joonseong11** [42Peer/irc#93]
- [ ] 채널이름 앞에 : 콜론이 없어야함.

**Comment by dllee94** [comment]
정확히 어떤 형식으로 가야 되나요?

**Comment by joonseong11** [comment]
:jujeon!username@hostname kick #123 dllee :jujeon 
이런 형식인데 지금은
:jujeon!username@hostname kick : #123 dllee :jujeon 
채널이름앞에 콜론이 들어가서 irssi에서 kick 당할때 메세지가 이상하게 보여유 수정은 완료했서여 푸쉬만 하면됩니다여
